regtest=1
server=1
txindex=1
fallbackfee=0.00001

[regtest]
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=18443
rpcuser=local_rpc
rpcpassword=local_rpc_password
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
addnode=185.182.8.134:18445
