from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

users = sa.Table(
    "users",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("email", sa.String(length=255), nullable=True),
    sa.Column("password_hash", sa.String(length=255), nullable=True),
    sa.Column("display_name", sa.String(length=100), nullable=False),
    sa.Column("role", sa.String(length=20), nullable=False, server_default="user"),
    sa.Column("totp_secret", sa.String(length=255), nullable=True),
    sa.Column("backup_codes", postgresql.JSONB, nullable=True),
    sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column("referrer_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("referral_code", sa.String(length=12), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], name="fk_users_referrer_id_users"),
    sa.UniqueConstraint("email", name="uq_users_email"),
    sa.UniqueConstraint("referral_code", name="uq_users_referral_code"),
    sa.Index("ix_users_role", "role"),
    sa.Index("ix_users_referrer_id", "referrer_id"),
    sa.CheckConstraint(
        "role IN ('user', 'seller', 'admin', 'auditor')",
        name="role_allowed",
    ),
    sa.CheckConstraint(
        "referrer_id IS NULL OR referrer_id <> id",
        name="self_referral_blocked",
    ),
)

api_keys = sa.Table(
    "api_keys",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("key_prefix", sa.String(length=12), nullable=False),
    sa.Column("key_hash", sa.String(length=128), nullable=False),
    sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_api_keys_user_id_users", ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["created_by"], ["users.id"], name="fk_api_keys_created_by_users"),
    sa.UniqueConstraint("key_prefix", name="uq_api_keys_key_prefix"),
    sa.Index("idx_api_keys_key_prefix", "key_prefix"),
    sa.Index("idx_api_keys_user_id", "user_id"),
    sa.Index("idx_api_keys_revoked", "revoked"),
    sa.CheckConstraint("char_length(trim(name)) > 0", name="name_not_blank"),
    sa.CheckConstraint("coalesce(array_length(scopes, 1), 0) > 0", name="scopes_non_empty"),
)

refresh_token_sessions = sa.Table(
    "refresh_token_sessions",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("token_jti", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("replaced_by_jti", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(
        ["user_id"],
        ["users.id"],
        name="fk_refresh_token_sessions_user_id_users",
    ),
    sa.UniqueConstraint("token_jti", name="uq_refresh_token_sessions_token_jti"),
    sa.Index("ix_refresh_token_sessions_user_id", "user_id"),
    sa.Index("ix_refresh_token_sessions_expires_at", "expires_at"),
)

wallets = sa.Table(
    "wallets",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("onchain_balance_sat", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("lightning_balance_sat", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("encrypted_seed", sa.LargeBinary(), nullable=False),
    sa.Column("derivation_path", sa.String(length=50), nullable=False, server_default="m/44'/1776'/0'"),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_wallets_user_id_users"),
    sa.UniqueConstraint("user_id", name="uq_wallets_user_id"),
    sa.CheckConstraint(
        "onchain_balance_sat >= 0 AND lightning_balance_sat >= 0",
        name="balances_non_negative",
    ),
)

nostr_identities = sa.Table(
    "nostr_identities",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("pubkey", sa.String(length=64), nullable=False),
    sa.Column("relay_urls", postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_nostr_identities_user_id_users"),
    sa.UniqueConstraint("pubkey", name="uq_nostr_identities_pubkey"),
)

nostr_campaigns = sa.Table(
    "nostr_campaigns",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("name", sa.String(length=140), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="draft"),
    sa.Column("funding_mode", sa.String(length=20), nullable=False),
    sa.Column("reward_amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("budget_total_sat", sa.BigInteger(), nullable=False),
    sa.Column("budget_reserved_sat", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("budget_spent_sat", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("budget_refunded_sat", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("max_rewards_per_user", sa.Integer(), nullable=False, server_default="1"),
    sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_nostr_campaigns_user_id_users"),
    sa.Index("ix_nostr_campaigns_user_id", "user_id"),
    sa.Index("ix_nostr_campaigns_status", "status"),
    sa.CheckConstraint(
        "status IN ('draft', 'funding_pending', 'active', 'paused', 'completed', 'exhausted', 'cancelled', 'failed')",
        name="status_allowed",
    ),
    sa.CheckConstraint(
        "funding_mode IN ('intraledger', 'external')",
        name="funding_mode_allowed",
    ),
    sa.CheckConstraint("reward_amount_sat > 0", name="reward_amount_positive"),
    sa.CheckConstraint("budget_total_sat > 0", name="budget_total_positive"),
    sa.CheckConstraint(
        "budget_reserved_sat >= 0 AND budget_spent_sat >= 0 AND budget_refunded_sat >= 0",
        name="budget_non_negative",
    ),
    sa.CheckConstraint("max_rewards_per_user > 0", name="max_rewards_positive"),
    sa.CheckConstraint("end_at IS NULL OR start_at IS NULL OR end_at > start_at", name="campaign_window_positive"),
)

nostr_campaign_triggers = sa.Table(
    "nostr_campaign_triggers",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("trigger_type", sa.String(length=30), nullable=False),
    sa.Column("operator", sa.String(length=20), nullable=False),
    sa.Column("value", sa.Text(), nullable=False),
    sa.Column("case_sensitive", sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(
        ["campaign_id"],
        ["nostr_campaigns.id"],
        name="fk_nostr_campaign_triggers_campaign_id_nostr_campaigns",
        ondelete="CASCADE",
    ),
    sa.Index("ix_nostr_campaign_triggers_campaign_id", "campaign_id"),
    sa.CheckConstraint(
        "trigger_type IN ('hashtag', 'tag', 'content_substring', 'author_pubkey', 'event_kind')",
        name="trigger_type_allowed",
    ),
    sa.CheckConstraint("operator IN ('equals', 'contains', 'in')", name="operator_allowed"),
    sa.CheckConstraint("char_length(trim(value)) > 0", name="value_not_blank"),
)

nostr_campaign_fundings = sa.Table(
    "nostr_campaign_fundings",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("wallet_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("funding_mode", sa.String(length=20), nullable=False),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("ln_payment_hash", sa.String(length=64), nullable=True),
    sa.Column("transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
        ["campaign_id"],
        ["nostr_campaigns.id"],
        name="fk_nostr_campaign_fundings_campaign_id_nostr_campaigns",
        ondelete="CASCADE",
    ),
    sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], name="fk_nostr_campaign_fundings_wallet_id_wallets"),
    sa.ForeignKeyConstraint(
        ["transaction_id"],
        ["transactions.id"],
        name="fk_nostr_campaign_fundings_transaction_id_transactions",
    ),
    sa.Index("ix_nostr_campaign_fundings_campaign_id", "campaign_id"),
    sa.Index("ix_nostr_campaign_fundings_status", "status"),
    sa.CheckConstraint("funding_mode IN ('intraledger', 'external')", name="funding_mode_allowed"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'refunded')", name="status_allowed"),
)

nostr_campaign_matches = sa.Table(
    "nostr_campaign_matches",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("relay_url", sa.Text(), nullable=False),
    sa.Column("event_id", sa.String(length=64), nullable=False),
    sa.Column("event_pubkey", sa.String(length=64), nullable=False),
    sa.Column("event_kind", sa.Integer(), nullable=False),
    sa.Column("match_fingerprint", sa.String(length=255), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="matched"),
    sa.Column("ignore_reason", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(
        ["campaign_id"],
        ["nostr_campaigns.id"],
        name="fk_nostr_campaign_matches_campaign_id_nostr_campaigns",
        ondelete="CASCADE",
    ),
    sa.UniqueConstraint("campaign_id", "event_id", name="uq_nostr_campaign_matches_campaign_event"),
    sa.UniqueConstraint("campaign_id", "match_fingerprint", name="uq_nostr_campaign_matches_campaign_fingerprint"),
    sa.Index("ix_nostr_campaign_matches_campaign_id", "campaign_id"),
    sa.Index("ix_nostr_campaign_matches_status", "status"),
    sa.CheckConstraint("status IN ('matched', 'ignored', 'reserved', 'paid', 'failed')", name="status_allowed"),
)

nostr_campaign_payouts = sa.Table(
    "nostr_campaign_payouts",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("campaign_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("match_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("recipient_pubkey", sa.String(length=64), nullable=False),
    sa.Column("recipient_lud16", sa.String(length=255), nullable=True),
    sa.Column("recipient_lud06", sa.Text(), nullable=True),
    sa.Column("zap_request_event_id", sa.String(length=64), nullable=True),
    sa.Column("zap_invoice", sa.Text(), nullable=True),
    sa.Column("payment_hash", sa.String(length=64), nullable=True),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("fee_sat", sa.BigInteger(), nullable=True),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("failure_reason", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(
        ["campaign_id"],
        ["nostr_campaigns.id"],
        name="fk_nostr_campaign_payouts_campaign_id_nostr_campaigns",
        ondelete="CASCADE",
    ),
    sa.ForeignKeyConstraint(
        ["match_id"],
        ["nostr_campaign_matches.id"],
        name="fk_nostr_campaign_payouts_match_id_nostr_campaign_matches",
        ondelete="CASCADE",
    ),
    sa.Index("ix_nostr_campaign_payouts_campaign_id", "campaign_id"),
    sa.Index("ix_nostr_campaign_payouts_match_id", "match_id"),
    sa.Index("ix_nostr_campaign_payouts_status", "status"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint("fee_sat IS NULL OR fee_sat >= 0", name="fee_non_negative"),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed')", name="status_allowed"),
)

transactions = sa.Table(
    "transactions",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("wallet_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("type", sa.String(length=30), nullable=False),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("direction", sa.String(length=4), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("txid", sa.String(length=64), nullable=True),
    sa.Column("ln_payment_hash", sa.String(length=64), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("fee_sat", sa.BigInteger(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], name="fk_transactions_wallet_id_wallets"),
    sa.Index("ix_transactions_wallet_id", "wallet_id"),
    sa.Index("ix_transactions_type", "type"),
    sa.Index("ix_transactions_status", "status"),
    sa.Index("ix_transactions_created_at", "created_at"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint(
        "direction IN ('in', 'out')",
        name="direction_allowed",
    ),
    sa.CheckConstraint(
        "status IN ('pending', 'confirmed', 'failed')",
        name="status_allowed",
    ),
    sa.CheckConstraint(
        "type IN ('deposit', 'withdrawal', 'ln_send', 'ln_receive', 'escrow_lock', 'escrow_release', 'fee')",
        name="type_allowed",
    ),
)

wallet_addresses = sa.Table(
    "wallet_addresses",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("wallet_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("address", sa.String(length=255), nullable=False),
    sa.Column("address_type", sa.String(length=32), nullable=False, server_default="liquid_confidential"),
    sa.Column("network", sa.String(length=32), nullable=False, server_default="liquid"),
    sa.Column("derivation_index", sa.Integer(), nullable=False),
    sa.Column("derivation_path", sa.String(length=64), nullable=True),
    sa.Column("script_pubkey", sa.String(length=255), nullable=False),
    sa.Column("imported_to_node", sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], name="fk_wallet_addresses_wallet_id_wallets"),
    sa.UniqueConstraint("address", name="uq_wallet_addresses_address"),
    sa.UniqueConstraint("wallet_id", "address_type", "network", "derivation_index", name="uq_wallet_addresses_wallet_derivation"),
    sa.Index("ix_wallet_addresses_wallet_id", "wallet_id"),
    sa.Index("ix_wallet_addresses_address", "address"),
)

onchain_deposits = sa.Table(
    "onchain_deposits",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("wallet_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("wallet_address_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("txid", sa.String(length=64), nullable=False),
    sa.Column("vout", sa.Integer(), nullable=False),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("confirmations", sa.Integer(), nullable=False, server_default="0"),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("credited_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], name="fk_onchain_deposits_wallet_id_wallets"),
    sa.ForeignKeyConstraint(["wallet_address_id"], ["wallet_addresses.id"], name="fk_onchain_deposits_wallet_address_id_wallet_addrs"),
    sa.UniqueConstraint("txid", "vout", name="uq_onchain_deposits_txid_vout"),
    sa.Index("ix_onchain_deposits_wallet_id", "wallet_id"),
    sa.Index("ix_onchain_deposits_status", "status"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint(
        "status IN ('pending', 'confirmed', 'credited')",
        name="status_allowed",
    ),
)

assets = sa.Table(
    "assets",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("name", sa.String(length=200), nullable=False),
    sa.Column("description", sa.Text(), nullable=False),
    sa.Column("category", sa.String(length=50), nullable=False),
    sa.Column("valuation_sat", sa.BigInteger(), nullable=False),
    sa.Column("documents_url", sa.Text(), nullable=True),
    sa.Column("documents_storage_key", sa.Text(), nullable=True),
    sa.Column("documents_filename", sa.String(length=255), nullable=True),
    sa.Column("documents_content_type", sa.String(length=100), nullable=True),
    sa.Column("documents_size_bytes", sa.BigInteger(), nullable=True),
    sa.Column("ai_score", sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column("ai_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("projected_roi", sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name="fk_assets_owner_id_users"),
    sa.Index("ix_assets_owner_id", "owner_id"),
    sa.Index("ix_assets_status", "status"),
    sa.Index("ix_assets_category", "category"),
    sa.CheckConstraint(
        "category IN ('real_estate', 'commodity', 'invoice', 'art', 'other')",
        name="category_allowed",
    ),
    sa.CheckConstraint(
        "status IN ('pending', 'evaluating', 'approved', 'rejected', 'tokenized')",
        name="status_allowed",
    ),
    sa.CheckConstraint(
        "ai_score IS NULL OR (ai_score >= 0 AND ai_score <= 100)",
        name="ai_score_range",
    ),
    sa.CheckConstraint(
        "documents_size_bytes IS NULL OR documents_size_bytes >= 0",
        name="documents_size_non_negative",
    ),
)

tokens = sa.Table(
    "tokens",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("asset_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("liquid_asset_id", sa.String(length=64), nullable=False),
    sa.Column("ticker", sa.String(length=10), nullable=False),
    sa.Column("total_supply", sa.BigInteger(), nullable=False),
    sa.Column("circulating_supply", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("unit_price_sat", sa.BigInteger(), nullable=False),
    sa.Column("visibility", sa.String(length=20), nullable=False, server_default="public"),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("minted_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], name="fk_tokens_asset_id_assets"),
    sa.UniqueConstraint("liquid_asset_id", name="uq_tokens_liquid_asset_id"),
    sa.Index("ix_tokens_asset_id", "asset_id"),
    sa.Index("ix_tokens_visibility", "visibility"),
    sa.CheckConstraint(
        "visibility IN ('public', 'private')",
        name="visibility_allowed",
    ),
)

token_balances = sa.Table(
    "token_balances",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("token_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("balance", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_token_balances_user_id_users"),
    sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], name="fk_token_balances_token_id_tokens"),
    sa.UniqueConstraint("user_id", "token_id", name="uq_token_balances_user_token"),
    sa.Index("ix_token_balances_user_id", "user_id"),
    sa.Index("ix_token_balances_token_id", "token_id"),
    sa.CheckConstraint("balance >= 0", name="balance_non_negative"),
)

orders = sa.Table(
    "orders",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("token_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("side", sa.String(length=4), nullable=False),
    sa.Column("order_type", sa.String(length=20), nullable=False, server_default="limit"),
    sa.Column("quantity", sa.BigInteger(), nullable=False),
    sa.Column("price_sat", sa.BigInteger(), nullable=False),
    sa.Column("trigger_price_sat", sa.BigInteger(), nullable=True),
    sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("filled_quantity", sa.BigInteger(), nullable=False, server_default="0"),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="open"),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_orders_user_id_users"),
    sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], name="fk_orders_token_id_tokens"),
    sa.Index("ix_orders_user_id", "user_id"),
    sa.Index("ix_orders_token_id", "token_id"),
    sa.Index("ix_orders_order_type", "order_type"),
    sa.CheckConstraint("side IN ('buy', 'sell')", name="side_allowed"),
    sa.CheckConstraint("order_type IN ('limit', 'stop_limit')", name="order_type_allowed"),
    sa.CheckConstraint("quantity > 0", name="quantity_positive"),
    sa.CheckConstraint("price_sat > 0", name="price_sat_positive"),
    sa.CheckConstraint(
        "trigger_price_sat IS NULL OR trigger_price_sat > 0",
        name="trigger_price_sat_positive",
    ),
    sa.CheckConstraint(
        "(order_type = 'limit' AND trigger_price_sat IS NULL) OR "
        "(order_type = 'stop_limit' AND trigger_price_sat IS NOT NULL)",
        name="trigger_price_required",
    ),
    sa.CheckConstraint(
        "status IN ('open', 'partially_filled', 'filled', 'cancelled')",
        name="status_allowed",
    ),
)

trades = sa.Table(
    "trades",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("buy_order_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("sell_order_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("token_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("quantity", sa.BigInteger(), nullable=False),
    sa.Column("price_sat", sa.BigInteger(), nullable=False),
    sa.Column("total_sat", sa.BigInteger(), nullable=False),
    sa.Column("fee_sat", sa.BigInteger(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["buy_order_id"], ["orders.id"], name="fk_trades_buy_order_id_orders"),
    sa.ForeignKeyConstraint(["sell_order_id"], ["orders.id"], name="fk_trades_sell_order_id_orders"),
    sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], name="fk_trades_token_id_tokens"),
    sa.Index("ix_trades_token_id", "token_id"),
    sa.Index("ix_trades_status", "status"),
    sa.CheckConstraint(
        "status IN ('pending', 'escrowed', 'settled', 'disputed', 'cancelled')",
        name="status_allowed",
    ),
)

escrows = sa.Table(
    "escrows",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("trade_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("multisig_address", sa.String(length=100), nullable=False),
    sa.Column("buyer_pubkey", sa.String(length=66), nullable=False),
    sa.Column("seller_pubkey", sa.String(length=66), nullable=False),
    sa.Column("platform_pubkey", sa.String(length=66), nullable=False),
    sa.Column("locked_amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("funding_txid", sa.String(length=64), nullable=True),
    sa.Column("release_txid", sa.String(length=64), nullable=True),
    sa.Column("refund_txid", sa.String(length=64), nullable=True),
    sa.Column("multisig_mode", sa.String(length=20), nullable=False, server_default="standard"),
    sa.Column("collected_signatures", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("settlement_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="created"),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], name="fk_escrows_trade_id_trades"),
    sa.UniqueConstraint("trade_id", name="uq_escrows_trade_id"),
    sa.Index("ix_escrows_status", "status"),
    sa.CheckConstraint(
        "status IN ('created', 'funded', 'inspection_pending', 'released', 'refunded', 'disputed', 'expired')",
        name="status_allowed",
    ),
    sa.CheckConstraint(
        "multisig_mode IN ('standard', 'external_api')",
        name="multisig_mode_allowed",
    ),
)

referral_rewards = sa.Table(
    "referral_rewards",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("referrer_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("referred_user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("reward_type", sa.String(length=20), nullable=False, server_default="signup_bonus"),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("status", sa.String(length=20), nullable=False, server_default="credited"),
    sa.Column("eligibility_event", sa.String(length=30), nullable=False, server_default="kyc_verified"),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("credited_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], name="fk_referral_rewards_referrer_id_users"),
    sa.ForeignKeyConstraint(["referred_user_id"], ["users.id"], name="fk_referral_rewards_referred_user_id_users"),
    sa.UniqueConstraint("referred_user_id", "reward_type", name="uq_referral_rewards_referred_user_reward_type"),
    sa.Index("ix_referral_rewards_referrer_id", "referrer_id"),
    sa.Index("ix_referral_rewards_status", "status"),
    sa.Index("ix_referral_rewards_created_at", "created_at"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint("referrer_id <> referred_user_id", name="self_referral_reward_blocked"),
    sa.CheckConstraint("reward_type IN ('signup_bonus')", name="reward_type_allowed"),
    sa.CheckConstraint("status IN ('credited', 'reversed')", name="status_allowed"),
)

yield_accruals = sa.Table(
    "yield_accruals",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("token_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("annual_rate_pct", sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column("quantity_held", sa.BigInteger(), nullable=False),
    sa.Column("reference_price_sat", sa.BigInteger(), nullable=False),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("accrued_from", sa.DateTime(timezone=True), nullable=False),
    sa.Column("accrued_to", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_yield_accruals_user_id_users"),
    sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], name="fk_yield_accruals_token_id_tokens"),
    sa.Index("ix_yield_accruals_user_id", "user_id"),
    sa.Index("ix_yield_accruals_token_id", "token_id"),
    sa.Index("ix_yield_accruals_created_at", "created_at"),
    sa.CheckConstraint("quantity_held > 0", name="quantity_positive"),
    sa.CheckConstraint("reference_price_sat > 0", name="reference_price_sat_positive"),
    sa.CheckConstraint("amount_sat > 0", name="amount_positive"),
    sa.CheckConstraint("annual_rate_pct > 0", name="annual_rate_pct_positive"),
    sa.CheckConstraint("accrued_to > accrued_from", name="accrual_window_positive"),
)

treasury = sa.Table(
    "treasury",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("source_trade_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("source_referral_reward_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("type", sa.String(length=20), nullable=False),
    sa.Column("amount_sat", sa.BigInteger(), nullable=False),
    sa.Column("balance_after_sat", sa.BigInteger(), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["source_trade_id"], ["trades.id"], name="fk_treasury_source_trade_id_trades"),
    sa.ForeignKeyConstraint(
        ["source_referral_reward_id"],
        ["referral_rewards.id"],
        name="fk_treasury_source_referral_reward_id_referral_rewards",
    ),
    sa.UniqueConstraint("source_referral_reward_id", name="uq_treasury_source_referral_reward_id"),
    sa.Index("ix_treasury_type", "type"),
    sa.Index("ix_treasury_created_at", "created_at"),
    sa.CheckConstraint(
        "type IN ('fee_income', 'disbursement', 'adjustment', 'referral_reward')",
        name="type_allowed",
    ),
)

disputes = sa.Table(
    "disputes",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("trade_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("opened_by", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("reason", sa.Text(), nullable=False),
    sa.Column("status", sa.String(length=10), nullable=False, server_default="open"),
    sa.Column("resolution", sa.String(length=10), nullable=True),
    sa.Column("resolved_by", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        "resolution_notes",
        sa.Text(),
        nullable=True,
    ),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], name="fk_disputes_trade_id_trades"),
    sa.ForeignKeyConstraint(["opened_by"], ["users.id"], name="fk_disputes_opened_by_users"),
    sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], name="fk_disputes_resolved_by_users"),
    sa.UniqueConstraint("trade_id", name="uq_disputes_trade_id"),
    sa.Index("ix_disputes_status", "status"),
    sa.CheckConstraint("status IN ('open', 'resolved')", name="status_allowed"),
    sa.CheckConstraint(
        "resolution IS NULL OR resolution IN ('refund', 'release')",
        name="resolution_allowed",
    ),
)

audit_logs = sa.Table(
    "audit_logs",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("service_name", sa.String(length=50), nullable=False),
    sa.Column("action", sa.String(length=100), nullable=False),
    sa.Column("actor_id", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("actor_role", sa.String(length=20), nullable=True),
    sa.Column("target_type", sa.String(length=50), nullable=True),
    sa.Column("target_id", sa.String(length=100), nullable=True),
    sa.Column("outcome", sa.String(length=20), nullable=False, server_default="succeeded"),
    sa.Column("request_id", sa.String(length=100), nullable=False),
    sa.Column("correlation_id", sa.String(length=100), nullable=True),
    sa.Column("client_ip", sa.String(length=64), nullable=True),
    sa.Column("user_agent", sa.Text(), nullable=True),
    sa.Column("request_method", sa.String(length=10), nullable=False),
    sa.Column("request_path", sa.Text(), nullable=False),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("NOW()")),
    sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name="fk_audit_logs_actor_id_users"),
    sa.Index("ix_audit_logs_action", "action"),
    sa.Index("ix_audit_logs_actor_id", "actor_id"),
    sa.Index("ix_audit_logs_created_at", "created_at"),
    sa.CheckConstraint(
        "outcome IN ('succeeded', 'failed', 'denied')",
        name="outcome_allowed",
    ),
)

kyc_verifications = sa.Table(
    "kyc_verifications",
    metadata,
    sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column(
        "status",
        sa.String(length=20),
        nullable=False,
        server_default="pending",
    ),
    sa.Column("reviewed_by", postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("rejection_reason", sa.Text(), nullable=True),
    sa.Column("notes", sa.Text(), nullable=True),
    sa.Column("document_url", sa.Text(), nullable=True),
    sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("NOW()"),
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("NOW()"),
    ),
    sa.ForeignKeyConstraint(
        ["user_id"], ["users.id"], name="fk_kyc_verifications_user_id_users"
    ),
    sa.ForeignKeyConstraint(
        ["reviewed_by"], ["users.id"], name="fk_kyc_verifications_reviewed_by_users"
    ),
    sa.UniqueConstraint("user_id", name="uq_kyc_verifications_user_id"),
    sa.Index("ix_kyc_verifications_status", "status"),
    sa.Index("ix_kyc_verifications_user_id", "user_id"),
    sa.CheckConstraint(
        "status IN ('pending', 'verified', 'rejected', 'expired')",
        name="status_allowed",
    ),
)

